### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by adityalahiri** [d909b/cxplain#3] opened 2020-02-16 19:06 UTC
I am getting some errors in tensorflow. Can you please tell which version of tensorflow was used while writing the notebooks?

**Comment by d909b** [comment] 2020-02-17 00:24
Thank you for opening an issue. The notebooks have been built against multiple TF versions.

Which TF version are you using? What errors are you seeing?

**Comment by mansourehk** [comment] 2020-02-18 15:55
I am getting some error because of the Tensorflow version, as well.
This is the error message: "TypeError: Incompatible types: <dtype: 'string'> vs. object. Value is" which appears after running the "explainer.fit(x_train, y_train);" line.

**Comment by d909b** [comment] 2020-02-18 16:15
@mansourehk Thank you for your comment. To reproduce this error, it would be good if you could share with me which code you were running before you encountered the error and which version of TF and Python you were using. Many thanks!

**Comment by mansourehk** [comment] 2020-02-18 16:19
> @mansourehk Thank you for your comment. To reproduce this error, it would be good if you could share with me which code you were running before you encountered the error and which version of TF and Python you were using. Many thanks!

I faced this issue while running both the "cifar10.ipynb" and "boston_housing.ipynb" example codes. I am using python 3.7 with the latest TensorFlow version, 2.1.0. I also tried TensorFlow 1.14.0 which was listed in the setup.py, still get the same error

**Comment by d909b** [comment] 2020-02-18 17:35
@mansourehk Thank you - I had a quick look and was not able to reproduce the exception yet using Python 3.7.5 and TF 1.14.0. Could you share the entire exception stack trace with me as well so that I can try to pin point the differences in setup?

**Comment by mansourehk** [comment] 2020-02-18 17:54
> @mansourehk Thank you - I had a quick look and was not able to reproduce the exception yet using Python 3.7.5 and TF 1.14.0. Could you share the entire exception stack trace with me as well so that I can try to pin point the differences in setup?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-ddabe152030a> in <module>
      1 explainer = CXPlain(explained_model, model_builder, masking_operation, loss, 
      2                     num_models=5, downsample_factors=downsample_factors, flatten_for_explained_model=True)
----> 3 explainer.fit(x_train, y_train);

~\AppData\Local\Continuum\anaconda3\lib\site-packages\cxplain\explanation_model.py in fit(self, X, y, masked_data)
    130         else:
    131             for model in self.model:
--> 132                 self._fit_single(model, X, y, masked_data=masked_data)
    133                 masked_data = self.get_masked_data()
    134         return self

~\AppData\Local\Continuum\anaconda3\lib\site-packages\cxplain\backend\tensorflow_cxplain.py in _fit_single(self, model, X, y, masked_data)
    177                 model_filepath = self.model_filepath
    178 
--> 179             self.last_history = self.model_builder.fit(model, masked_data, y, model_filepath)
    180         return self
    181 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\cxplain\backend\model_builders\base_model_builder.py in fit(self, model, precomputed, y, model_filepath)
    170         # Perform an initial model save so that one version of the model is always saved
    171         # even if model fitting or check-pointing fails.
--> 172         model.save_weights(model_filepath)
    173 
    174         history = model.fit(x=precomputed,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py in save_weights(self, filepath, overwrite, save_format)
   1429              'saved.\n\nConsider using a TensorFlow optimizer from `tf.train`.')
   1430             % (optimizer,))
-> 1431       self._checkpointable_saver.save(filepath, session=session)
   1432       # Record this checkpoint so it's visible from tf.train.latest_checkpoint.
   1433       checkpoint_management.update_checkpoint_state(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\training\checkpointable\util.py in save(self, file_prefix, checkpoint_number, session)
   1489         with ops.device("/cpu:0"):
   1490           self._object_graph_feed_tensor = constant_op.constant(
-> 1491               "", dtype=dtypes.string)
   1492           self._file_prefix_feed_tensor = constant_op.constant(
   1493               "", dtype=dtypes.string)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name)
    243   """
    244   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 245                         allow_broadcast=True)
    246 
    247 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    281       tensor_util.make_tensor_proto(
    282           value, dtype=dtype, shape=shape, verify_shape=verify_shape,
--> 283           allow_broadcast=allow_broadcast))
    284   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    285   const_tensor = g.create_op(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)
    499                             dtype.base_dtype != numpy_dtype.base_dtype):
    500     raise TypeError("Incompatible types: %s vs. %s. Value is %s" %
--> 501                     (dtype, nparray.dtype, values))
    502 
    503   # If shape is not given, get the shape from the numpy array.

TypeError: Incompatible types: <dtype: 'string'> vs. object. Value is

**Comment by d909b** [comment] 2020-02-19 18:31
@mansourehk Thank you. That looks like an error with your TF installation since the exception is happening in `Model.save_weights()`. Are you able to reinstall TF? I have so far not been able to reproduce this exception with TF 1.14 and TF 2.0. Using TF 2.1, there seems to be an unrelated exception during training that I will investigate further.

@arrayslayer Is this the same error you have been experiencing? Please share your exception trace as well for me to investigate. Many thanks!

**Comment by adityalahiri** [comment] 2020-02-20 15:26
@d909b  No this wasn't exactly my error. I had like 2-3 of them which I solved after googling them. They were related to new tensorflow versions and were fairly common to debug. Thanks!

**Comment by d909b** [comment] 2020-02-23 19:29
@arrayslayer Cool, thank you.

Closing this issue since the exceptions were due to TF install problems and not directly related to CXPlain.

**Closed as completed by d909b** 2020-02-23 19:29 UTC
